--- 
- hosts: homeassistant
  pre_tasks: 
    - include: vars/tor.yml
    - include: vars/main.yml
    - include: vars/hass.yml
  roles:
    - homeassistant
    - toke.tor
  tasks: 
    - name: Install required packages
      package:
        name: '{{ item }}'
        state: latest
      loop: 
        - '{{ packages }}'

    - name: Update motd
      template: 
        src: 'motd.j2'
        dest: /etc/motd
