---

- hosts: relays
  vars:
    #tor_ContactInfo: relayor-example@example.com
    tor_signingkeylifetime_days: 90
    tor_nickname: "{{ ansible_hostname }}"
    tor_ports:
        - { orport: 443, dirport: 80}
  roles:
   - nusenu.relayor
